CREATE PROC FI_SP_ConsBeneficiario
	@ID BIGINT,
	@CPF VARCHAR(11)
AS
BEGIN
IF (ISNULL(@ID,0) <> 0 AND ISNULL(@CPF, '') <> '')
        SELECT NOME, CPF, ID, IDCLIENTE  FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID AND CPF = @CPF
ELSE
		SELECT NOME, CPF, ID, IDCLIENTE  FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID OR CPF = @CPF
END